export const mockQuizzes = [
  {
    articleId: 'lumen-science',
    questions: [
      {
        id: 'q-lumen-1',
        text: 'What primary physical phenomenon does the Lumen technique utilize to trace neurological activity?',
        options: [
          'Fluorescence microscopy',
          'Quantum bioluminescence',
          'Positron emission tomography',
          'Magnetic resonance relaxation'
        ],
        correctAnswerIndex: 1,
        explanation: 'Lumen leverages quantum bioluminescence to illuminate synapses in real-time, relying on engineered proteins that emit light when neurotransmitters bind to them.'
      },
      {
        id: 'q-lumen-2',
        text: 'How does Lumen allow researchers to view functional neural activity at the level of individual synapses?',
        options: [
          'By utilizing engineered proteins that emit photons upon neurotransmitter binding',
          'By injecting radioactive dyes that concentrate in blood vessels',
          'By using deep-penetrating infrared radiation to heat active neurons',
          'By tracking external electromagnetic fields generated by the skull'
        ],
        correctAnswerIndex: 0,
        explanation: 'Engineered proteins bind to neurotransmitters and emit photons, rendering synaptic transmissions visible as light waves.'
      },
      {
        id: 'q-lumen-3',
        text: 'According to the article, what is the ultimate therapeutic goal of tracking sensory data transmission with Lumen?',
        options: [
          'Enhancing human sensory capabilities beyond normal limits',
          'Developing bio-optical computer processors',
          'Understanding cellular mechanics to treat neurodegenerative conditions',
          'Creating artificial brain tissue structures'
        ],
        correctAnswerIndex: 2,
        explanation: 'The article notes that tracking sensory data transmission to memory formation opens new horizons in treating neurodegenerative conditions.'
      }
    ]
  },
  {
    articleId: 'ai-revolution',
    questions: [
      {
        id: 'q-ai-1',
        text: 'What major paradigm shift in AI workflows does the article describe?',
        options: [
          'From deep neural networks to rule-based expert systems',
          'From cloud computing to client-server database architectures',
          'From static conversational prompts to dynamic, multi-step agentic workflows',
          'From custom silicon to standard general-purpose CPUs'
        ],
        correctAnswerIndex: 2,
        explanation: 'The next wave of AI focuses on agentic workflows where systems execute multi-step plans, reflect on their output, and use external tools.'
      },
      {
        id: 'q-ai-2',
        text: 'What is a key benefit of running powerful lightweight models locally?',
        options: [
          'They eliminate the need for any storage drive space',
          'They provide privacy-first, low-latency intelligence independent of cloud connectivity',
          'They require zero electrical power to run',
          'They are automatically more accurate than large cloud-based models'
        ],
        correctAnswerIndex: 1,
        explanation: 'Local models running on consumer hardware offer low-latency, privacy-first intelligence without depending on cloud servers.'
      },
      {
        id: 'q-ai-3',
        text: 'How do "agentic" AI systems differ from standard conversational models?',
        options: [
          'They use fewer parameters and require less training data',
          'They only respond in code instead of human language',
          'They plan, reflect, use tools, and cooperate with other models to complete tasks',
          'They run exclusively inside specialized database systems'
        ],
        correctAnswerIndex: 2,
        explanation: 'Agentic workflows distinguish themselves by planning, tool utilization, reflection, and collaboration instead of just doing single-turn responses.'
      }
    ]
  },
  {
    articleId: 'mindfulness-health',
    questions: [
      {
        id: 'q-mindfulness-1',
        text: 'Which brain region is observed to shrink in gray matter density with consistent mindfulness practice?',
        options: [
          'Prefrontal cortex',
          'Hippocampus',
          'Amygdala',
          'Occipital lobe'
        ],
        correctAnswerIndex: 2,
        explanation: 'Neuroimaging studies show a decrease in gray matter density in the amygdala, which plays a major role in the body\'s response to stress and anxiety.'
      },
      {
        id: 'q-mindfulness-2',
        text: 'What neural network system is active when we dwell on the past or worry about the future?',
        options: [
          'Central executive network (CEN)',
          'Default mode network (DMN)',
          'Salience network (SN)',
          'Somatic nervous system (SNS)'
        ],
        correctAnswerIndex: 1,
        explanation: 'The Default Mode Network (DMN) is the brain system highly active during mind-wandering, dwelling on the past, or projecting into the future.'
      },
      {
        id: 'q-mindfulness-3',
        text: 'What physical structural change is observed in the brain regions associated with attention during meditation?',
        options: [
          'Cortical thickening',
          'Ventricular expansion',
          'Cerebellar reduction',
          'Myelin breakdown'
        ],
        correctAnswerIndex: 0,
        explanation: 'Studies show cortical thickening in brain regions corresponding to attention and sensory processing as a result of consistent mindfulness practice.'
      }
    ]
  }
];
