import mongoose from 'mongoose'

const moderationResultSchema = new mongoose.Schema(
  {
    // ID of the original Article, Quiz, or Comment.
    // Kept as String so this module can work with existing IDs
    // without forcing changes to other modules.
    contentId: {
      type: String,
      default: null,
      index: true,
    },

    contentType: {
      type: String,
      enum: ['Article', 'Quiz', 'Comment'],
      required: true,
      index: true,
    },

    title: {
      type: String,
      default: '',
      trim: true,
    },

    content: {
      type: String,
      required: true,
    },

    authorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
      index: true,
    },

    authorName: {
      type: String,
      default: 'Unknown',
      trim: true,
    },

    // Normalized risk score from 0 to 1.
    riskScore: {
      type: Number,
      required: true,
      min: 0,
      max: 1,
    },

    riskLevel: {
      type: String,
      enum: ['LOW', 'MEDIUM', 'HIGH'],
      required: true,
      index: true,
    },

    // Recommendation generated by the moderation module.
    // Future Smart Approval can use this value.
    recommendation: {
      type: String,
      enum: ['SAFE', 'REVIEW', 'BLOCK'],
      required: true,
      index: true,
    },

    flags: {
      spam: {
        type: Boolean,
        default: false,
      },

      toxic: {
        type: Boolean,
        default: false,
      },

      hateSpeech: {
        type: Boolean,
        default: false,
      },

      inappropriate: {
        type: Boolean,
        default: false,
      },

      violence: {
        type: Boolean,
        default: false,
      },

      suspiciousLinks: {
        type: Boolean,
        default: false,
      },

      pii: {
        type: Boolean,
        default: false,
      },
    },

    // Individual category scores used by the
    // moderation review page and future analytics.
    categoryScores: {
      spam: {
        type: Number,
        default: 0,
        min: 0,
        max: 1,
      },

      harassment: {
        type: Number,
        default: 0,
        min: 0,
        max: 1,
      },

      hateSpeech: {
        type: Number,
        default: 0,
        min: 0,
        max: 1,
      },

      violence: {
        type: Number,
        default: 0,
        min: 0,
        max: 1,
      },

      adultContent: {
        type: Number,
        default: 0,
        min: 0,
        max: 1,
      },
    },

    // Indicates whether the AI moderation provider
    // itself flagged the submitted content.
    aiFlagged: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
)

export default mongoose.model('ModerationResult', moderationResultSchema)