import { useEffect, useState } from 'react'
import { quizService } from '../../services/quizService'

const newQuestion = () => ({ id: crypto.randomUUID(), text: '', options: ['', '', '', ''], correctAnswerIndex: 0, explanation: '' })
export default function AdminQuizEditor({ articleId, quiz, onSaved }) {
  const [questions, setQuestions] = useState(quiz?.questions || [])
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => setQuestions(quiz?.questions || []), [quiz])
  const updateQuestion = (index, field, value) => setQuestions(current => current.map((question, itemIndex) => itemIndex === index ? { ...question, [field]: value } : question))
  const updateOption = (questionIndex, optionIndex, value) => setQuestions(current => current.map((question, index) => index === questionIndex ? { ...question, options: question.options.map((option, itemIndex) => itemIndex === optionIndex ? value : option) } : question))
  async function save() { try { setSaving(true); setError(''); setMessage(''); const updated = await quizService.updateQuiz(articleId, questions); onSaved(updated); setMessage('Quiz saved. It will publish with the article when approved.') } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <section className="admin-quiz-editor"><div className="quiz-editor-heading"><div><span className="eyebrow">Admin quiz review</span><h2>{quiz ? 'Edit attached quiz.' : 'Add a quiz.'}</h2><p>Review the questions and correct answers before publishing.</p></div><button className="button" type="button" onClick={() => setQuestions(current => [...current, newQuestion()])}>Add question</button></div>{questions.length === 0 && <p className="quiz-attached-note">No quiz is attached. Add a question to create one.</p>}{questions.map((question, questionIndex) => <fieldset className="quiz-question-editor" key={question.id}><legend>Question {questionIndex + 1}</legend><label>Question<input value={question.text} onChange={(event) => updateQuestion(questionIndex, 'text', event.target.value)} /></label><div className="quiz-options">{question.options.map((option, optionIndex) => <label key={optionIndex}>Option {optionIndex + 1}<input value={option} onChange={(event) => updateOption(questionIndex, optionIndex, event.target.value)} /><span className="answer-choice"><input type="radio" name={`admin-correct-${question.id}`} checked={question.correctAnswerIndex === optionIndex} onChange={() => updateQuestion(questionIndex, 'correctAnswerIndex', optionIndex)} /> Correct answer</span></label>)}</div><label>Explanation<textarea rows="3" value={question.explanation} onChange={(event) => updateQuestion(questionIndex, 'explanation', event.target.value)} /></label><button className="quiz-remove" type="button" onClick={() => setQuestions(current => current.filter((_, index) => index !== questionIndex))}>Remove question</button></fieldset>)}{error && <p className="error">{error}</p>}{message && <p className="profile-success">{message}</p>}{questions.length > 0 && <button className="submit-button profile-save" type="button" disabled={saving} onClick={save}>{saving ? 'Saving…' : 'Save quiz changes'}</button>}</section>
}
