export const mockArticles = [
  {
    id: 'lumen-science',
    title: 'Lumen: Unleashing the Power of Synaptic Illumination',
    excerpt: 'How quantum bioluminescence is allowing researchers to observe neuro-chemical reactions in real-time, mapping thoughts as light.',
    body: 'For decades, tracing the intricate pathways of the human brain felt like trying to map a dense, dark forest during a storm. Traditional imaging techniques, while revolutionary, offered either high structural detail or real-time functional tracking, but rarely both at the scale of single synapses. Enter Lumen—a breakthrough technique in quantum bioluminescence that is changing everything.\n\nBy leveraging engineered proteins that emit photons when triggered by specific neurotransmitter binds, scientists can now illuminate active synapses in living tissue. The resulting images show thoughts not as abstract concepts, but as physical waves of light cascading through neural pathways. This article explores the biology, chemistry, and future computational models driving this neurotech revolution.\n\nIn early clinical models, researchers successfully tracked the transmission of sensory data from stimulus to response. The implication is profound: we are close to understanding the exact cellular mechanics of memory formation and retrieval. This opens new horizons in treating neurodegenerative conditions.',
    category: 'Science',
    tags: ['Neuroscience', 'Bioluminescence', 'Quantum Biology'],
    author: 'Dr. Evelyn Carter',
    status: 'Published',
    coverImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
    readMinutes: 6,
    views: 1240,
    publishedAt: '2026-08-25'
  },
  {
    id: 'ai-revolution',
    title: 'The AI Revolution: Beyond the Hype of Large Language Models',
    excerpt: 'An in-depth analysis of the next wave of artificial intelligence: agentic workflows, multi-modal reasoning, and local model orchestration.',
    body: 'While chat interfaces have captured the public imagination, the true transformation is happening under the hood. The paradigm is shifting from static, conversational LLMs to dynamic, agentic workflows.\n\nAgentic AI systems don\'t just respond to prompts; they execute multi-step plans, reflect on their own output, use external tools, and collaborate with other specialized models. This shift marks the beginning of AI systems capable of autonomous execution, making them active partners in development, research, and creative workflows.\n\nMoreover, the rise of powerful, lightweight local models is democratizing access. Run locally on standard consumer hardware, these models offer privacy-first, low-latency intelligence that doesn\'t depend on cloud connectivity. The implications for personal privacy and distributed computing are staggering.',
    category: 'Technology',
    tags: ['Artificial Intelligence', 'LLMs', 'Agentic AI'],
    author: 'Marcus Vance',
    status: 'Published',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    readMinutes: 8,
    views: 3105,
    publishedAt: '2026-08-20'
  },
  {
    id: 'mindfulness-health',
    title: 'Mindfulness in Modern Times: The Neurology of Stillness',
    excerpt: 'What happens to the brain during meditation? We look at cortical thickening, amygdala shrinkage, and the science of stress reduction.',
    body: 'In an era of constant connectivity and information overload, the ancient practice of mindfulness has transitioned from spiritual retreats to clinical psychology. But what does neuroscience say about it?\n\nStudies utilizing fMRI scans show that consistent mindfulness practice leads to structural changes in the brain. Most notably, researchers observe cortical thickening in areas associated with attention and sensory processing, and a corresponding decrease in gray matter density in the amygdala—the brain\'s alarm system for stress and anxiety.\n\nBy consciously training our attention on the present moment, we effectively rewire the default mode network (DMN), the system active when we dwell on the past or worry about the future. This physical reconfiguration explains why meditation reduces cortisol levels and fosters cognitive resilience.',
    category: 'Health',
    tags: ['Mindfulness', 'Neuroscience', 'Mental Health'],
    author: 'Sarah Jenkins',
    status: 'Published',
    coverImage: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
    readMinutes: 5,
    views: 942,
    publishedAt: '2026-08-18'
  },
  {
    id: 'renaissance-art',
    title: 'Lost Arts of the Renaissance: Tech That Time Forgot',
    excerpt: 'Uncovering the ingenious mechanisms, pigments, and engineering feats of 15th-century masters that were lost to history.',
    body: 'The Renaissance was a golden age of art and science, where the line between painter and engineer was practically nonexistent. While works like the Mona Lisa are household names, the technological innovations that enabled them are frequently overlooked.\n\nFrom elaborate pulley systems used to construct colossal cathedrals to secret chemical recipes for intense, lightfast pigments, the workshops of Florence and Venice were hotbeds of research and development. Some of these techniques, such as specific plaster compositions for frescoes and complex mechanical clocks, were kept so secret that they died with their inventors.\n\nToday, modern scholars are using multispectral imaging and chemical analysis to reverse-engineer these lost techniques, revealing that 15th-century masters possessed a sophisticated understanding of materials science.',
    category: 'Culture',
    tags: ['Renaissance', 'History', 'Art History'],
    author: 'Lorenzo Rossi',
    status: 'Published',
    coverImage: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
    readMinutes: 7,
    views: 750,
    publishedAt: '2026-08-10'
  },
  {
    id: 'crispr-gene-editing',
    title: 'Decoding CRISPR and Gene Editing: Ethical Frontiers',
    excerpt: 'A comprehensive guide to the current capabilities of CRISPR-Cas9, and the deep ethical dilemmas surrounding germline modification.',
    body: 'CRISPR-Cas9 has revolutionized molecular biology, acting as a molecular pair of scissors that can edit DNA with unprecedented precision. While the potential to cure genetic diseases is massive, it brings ethical questions that humanity is barely prepared to answer.',
    category: 'Science',
    tags: ['Genetics', 'CRISPR', 'Bioethics'],
    author: 'Dr. Evelyn Carter',
    status: 'Draft',
    coverImage: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?auto=format&fit=crop&w=800&q=80',
    readMinutes: 10,
    views: 0,
    publishedAt: null
  },
  {
    id: 'future-webdev',
    title: 'The Future of Web Development: Edge, WASM, and Beyond',
    excerpt: 'How serverless edge computing and WebAssembly are rewriting the rules of application performance and deployment architectures.',
    body: 'The modern web stack is evolving rapidly. Computations are moving away from centralized servers directly to the edge, closer to users. Meanwhile, WebAssembly (WASM) enables near-native performance inside the browser, unlocking new classes of web apps.',
    category: 'Technology',
    tags: ['WebDev', 'WASM', 'Edge Computing'],
    author: 'Marcus Vance',
    status: 'Pending',
    coverImage: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80',
    readMinutes: 6,
    views: 0,
    publishedAt: null
  },
  {
    id: 'nutrition-myths',
    title: 'Nutrition Myths Debunked: What Science Actually Says',
    excerpt: 'Separating dietary fads from metabolic reality. We review the evidence on intermittent fasting, carbs, and processing.',
    body: 'Dietary advice changes by the day, but metabolic biochemistry remains constant. In this article, we evaluate popular nutritional trends against peer-reviewed studies to help you understand what actually supports long-term health.',
    category: 'Health',
    tags: ['Nutrition', 'Diet', 'Metabolism'],
    author: 'Sarah Jenkins',
    status: 'Approved',
    coverImage: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80',
    readMinutes: 5,
    views: 0,
    publishedAt: null
  },
  {
    id: 'understanding-crypto',
    title: 'Understanding Cryptocurrency: Cryptographic Protocols',
    excerpt: 'A cold, technical breakdown of distributed consensus, proof algorithms, and smart contract verification mechanisms.',
    body: 'Cryptocurrencies are often discussed in terms of market value, but their underlying cryptographic structures represent major breakthroughs in computer science. We look at consensus engines and Byzantine fault tolerance.',
    category: 'Technology',
    tags: ['Blockchain', 'Cryptography', 'Consensus'],
    author: 'Marcus Vance',
    status: 'Rejected',
    coverImage: 'https://images.unsplash.com/photo-1516245834210-c4c142787335?auto=format&fit=crop&w=800&q=80',
    readMinutes: 9,
    views: 0,
    publishedAt: null
  },
  {
    id: 'exploring-deep-ocean',
    title: 'Exploring the Deep Ocean: The Abyssal Plains Ecosystem',
    excerpt: 'Investigating the extreme adaptations of hydrothermal vent organisms and the technology needed to survive absolute darkness.',
    body: 'The deep ocean is less mapped than the surface of Mars. At depths of several thousand meters, organisms survive crushing pressures, freezing temperatures, and total absence of sunlight. We examine the chemistry of life near geothermal vents.',
    category: 'Science',
    tags: ['Oceanography', 'Marine Biology', 'Abyssal Zone'],
    author: 'Dr. Evelyn Carter',
    status: 'Changes Requested',
    coverImage: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=800&q=80',
    readMinutes: 8,
    views: 0,
    publishedAt: null
  }
];
